"""
G1–G7 gate stack for the ORB entry decision.

Gates are evaluated in sequence every minute after the OR window closes.
The first failing gate short-circuits evaluation and returns a NO_TRADE result
with a specific reason code so the decision can be logged and audited.

Key design notes
----------------
- G4 (follow-through) now requires the PREVIOUS candle to have already confirmed
  the breakout — i.e. entry only fires on the second consecutive breakout candle.
  Pass prev_candle_close=None to skip this check (e.g. first OR-ready minute).

- G7 (target viability) now asks "can the spread theoretically earn at least the
  session target?" — NOT a fixed 1.5× R:R ratio.  This matches the PRD intent
  exactly: reject only when the spread is so wide that even a full move to max
  width cannot cover the session target.

- Candidate spreads: G5–G7 are evaluated against N_CANDIDATE_SPREADS strike
  pairs per direction (generated by opening_range.py helpers).  The first
  candidate that passes all three sub-gates is used for entry.

- lot_size comes in as a parameter (read from instruments master by paper_engine)
  so the engine stays correct even after Zerodha quarterly lot-size changes.
"""
import math
from dataclasses import dataclass, field
from datetime import date as date_type, time as time_type
from typing import Dict, List, Optional, Tuple

from app.services.opening_range import (
    STRIKE_STEP,
    generate_bearish_candidates,
    generate_bullish_candidates,
    is_bearish_breakout,
    is_bullish_breakout,
)

# ── Strategy config (sourced from central config) ─────────────────────────────
from app.services.strategy_config import STRATEGY_CONFIG as _CFG

MAX_RISK_PCT = _CFG["max_risk_pct"]        # G6: max 2% of capital as max loss
TARGET_PCT   = _CFG["target_profit_pct"]   # profit target = 0.5% of capital

_SQUARE_OFF_TIME           = _CFG["square_off_time"]            # 15:20
_MIN_MINUTES_LEFT_TO_ENTER = _CFG["min_minutes_left_to_enter"]  # reject if < 20 mins remain

# Fallback lot sizes — used only if instruments master lookup fails
_FALLBACK_LOT_SIZES: Dict[str, int] = _CFG["fallback_lot_sizes"]


def _minutes_until_squareoff(current_time: time_type) -> int:
    """Return minutes remaining from current_time until SQUARE_OFF_TIME (may be negative)."""
    sq  = _SQUARE_OFF_TIME.hour * 60 + _SQUARE_OFF_TIME.minute
    cur = current_time.hour * 60 + current_time.minute
    return sq - cur


# ── Result dataclass ──────────────────────────────────────────────────────────

@dataclass
class GateResult:
    action: str                            # "ENTER" or "NO_TRADE"
    reason_code: str
    reason_text: str
    # Populated on ENTER
    candidate_structure: Optional[Dict] = None
    computed_max_loss: Optional[float] = None
    computed_target: Optional[float] = None
    bias: Optional[str] = None
    long_strike: Optional[int] = None
    short_strike: Optional[int] = None
    opt_type: Optional[str] = None
    approved_lots: int = 0
    entry_debit: float = 0.0
    lot_size: int = 75
    expiry: Optional[date_type] = None
    # Pre-entry economics snapshot — populated even for NO_TRADE when we reached
    # G3+ so the audit log can surface "what the trade would have looked like"
    pre_entry_snapshot: Optional[Dict] = None


# ── Gate evaluator ────────────────────────────────────────────────────────────

def evaluate_gates(
    candle: Dict,
    or_high: float,
    or_low: float,
    or_ready: bool,
    has_open_trade: bool,
    option_prices: Dict,        # {(strike, opt_type): price}
    instrument: str,
    capital: float,
    expiry: date_type,
    prev_candle_close: Optional[float] = None,  # for G4 follow-through
    lot_size: Optional[int] = None,             # from instruments master
    current_time: Optional[time_type] = None,   # for TOO_LATE_TO_ENTER check
) -> GateResult:
    """
    Evaluate G1–G7 for the given minute candle.

    Returns GateResult(action="ENTER") if all gates pass, otherwise
    GateResult(action="NO_TRADE") with the first-failing reason code.

    For minutes that reach direction detection (G3+), pre_entry_snapshot is
    always populated so the audit log can surface rejected-trade economics.
    """
    close = float(candle["close"])
    lot_size = lot_size or _FALLBACK_LOT_SIZES.get(instrument, 75)
    risk_cap = capital * MAX_RISK_PCT
    target_rupees = capital * TARGET_PCT

    # ── G1: Opening range window complete ────────────────────────────────────
    if not or_ready:
        return GateResult(
            action="NO_TRADE",
            reason_code="OPENING_RANGE_NOT_READY",
            reason_text=(
                f"Opening range window not yet complete. "
                f"OR High={or_high:.2f}, Low={or_low:.2f}."
            ),
        )

    # ── G2: No active trade ───────────────────────────────────────────────────
    if has_open_trade:
        return GateResult(
            action="NO_TRADE",
            reason_code="ACTIVE_TRADE_EXISTS",
            reason_text="A paper trade is already open. Only one trade per session.",
        )

    # ── G2b: Enough time left before forced square-off ────────────────────────
    if current_time is not None:
        mins_left = _minutes_until_squareoff(current_time)
        if mins_left < _MIN_MINUTES_LEFT_TO_ENTER:
            return GateResult(
                action="NO_TRADE",
                reason_code="TOO_LATE_TO_ENTER",
                reason_text=(
                    f"Only {mins_left} minute(s) until square-off at "
                    f"{_SQUARE_OFF_TIME.strftime('%H:%M')}; "
                    f"need ≥ {_MIN_MINUTES_LEFT_TO_ENTER} to enter."
                ),
            )

    # ── G3: Spot has closed beyond OR boundary ────────────────────────────────
    bullish = is_bullish_breakout(close, or_high)
    bearish = is_bearish_breakout(close, or_low)
    if not bullish and not bearish:
        return GateResult(
            action="NO_TRADE",
            reason_code="NO_BREAKOUT_CONFIRMATION",
            reason_text=(
                f"Close {close:.2f} has not broken OR high {or_high:.2f} "
                f"(need >{or_high * 1.001:.2f}) or OR low {or_low:.2f} "
                f"(need <{or_low * 0.999:.2f})."
            ),
        )

    bias    = "BULLISH" if bullish else "BEARISH"
    opt_type = "CE" if bullish else "PE"

    # ── G4: Follow-through — second consecutive breakout candle required ───────
    # The first breakout candle is treated as tentative.  Only when the previous
    # candle also confirmed the same breakout do we proceed to trade evaluation.
    # (prev_candle_close=None on the very first OR-ready minute → skip check.)
    if prev_candle_close is not None:
        if bullish and not is_bullish_breakout(prev_candle_close, or_high):
            return GateResult(
                action="NO_TRADE",
                reason_code="FAILED_BREAKOUT_OR_NO_FOLLOWTHROUGH",
                reason_text=(
                    f"Tentative bullish breakout at {close:.2f} "
                    f"(OR high {or_high:.2f}).  Previous close {prev_candle_close:.2f} "
                    f"was inside range — waiting one more candle to confirm."
                ),
                pre_entry_snapshot={
                    "bias": bias, "opt_type": opt_type,
                    "or_high": round(or_high, 2), "or_low": round(or_low, 2),
                    "close": round(close, 2), "prev_close": round(prev_candle_close, 2),
                    "failing_gate": "G4",
                },
            )
        if bearish and not is_bearish_breakout(prev_candle_close, or_low):
            return GateResult(
                action="NO_TRADE",
                reason_code="FAILED_BREAKOUT_OR_NO_FOLLOWTHROUGH",
                reason_text=(
                    f"Tentative bearish breakout at {close:.2f} "
                    f"(OR low {or_low:.2f}).  Previous close {prev_candle_close:.2f} "
                    f"was inside range — waiting one more candle to confirm."
                ),
                pre_entry_snapshot={
                    "bias": bias, "opt_type": opt_type,
                    "or_high": round(or_high, 2), "or_low": round(or_low, 2),
                    "close": round(close, 2), "prev_close": round(prev_candle_close, 2),
                    "failing_gate": "G4",
                },
            )

    # ── G5–G7: Candidate spread evaluation ───────────────────────────────────
    # Iterate through N_CANDIDATE_SPREADS spread pairs per direction.
    # Accept the first pair that passes all three sub-gates so the engine
    # can enter even when the primary ATM spread fails (e.g. thin liquidity,
    # risk cap, or marginal target viability).
    candidates: List[Tuple[int, int]] = (
        generate_bullish_candidates(or_high)
        if bullish
        else generate_bearish_candidates(or_low)
    )

    last_fail_code = "NO_HEDGE_AVAILABLE"
    last_fail_text = (
        f"No viable option spread found for any of the {len(candidates)} "
        f"candidate strike pairs tried for {bias} direction."
    )
    best_snapshot: Optional[Dict] = None

    for rank, (long_s, short_s) in enumerate(candidates, start=1):
        long_p  = option_prices.get((long_s, opt_type))
        short_p = option_prices.get((short_s, opt_type))

        # ── G5: Both legs must have a valid price ─────────────────────────
        if long_p is None or short_p is None:
            continue
        long_p  = float(long_p)
        short_p = float(short_p)
        if long_p <= 0 or short_p <= 0:
            continue

        spread_debit = long_p - short_p
        if spread_debit <= 0:
            continue

        # ── G6: Max loss within risk cap ──────────────────────────────────
        max_loss_per_lot = spread_debit * lot_size
        approved_lots   = int(math.floor(risk_cap / max_loss_per_lot))
        if approved_lots == 0:
            last_fail_code = "RISK_EXCEEDS_CAP"
            last_fail_text = (
                f"Max loss per lot ₹{max_loss_per_lot:.0f} exceeds risk cap "
                f"₹{risk_cap:.0f} for {long_s}{opt_type}/{short_s}{opt_type}."
            )
            best_snapshot = {
                "bias": bias, "opt_type": opt_type,
                "candidate_rank": rank,
                "long_strike": long_s, "short_strike": short_s,
                "spread_width": abs(short_s - long_s),
                "long_price": round(long_p, 2), "short_price": round(short_p, 2),
                "spread_debit": round(spread_debit, 2),
                "max_loss_per_lot": round(max_loss_per_lot, 2),
                "risk_cap": round(risk_cap, 2),
                "target_rupees": round(target_rupees, 2),
                "failing_gate": "G6",
            }
            continue

        total_max_loss = approved_lots * max_loss_per_lot
        spread_width   = abs(short_s - long_s)           # e.g. 50 pts
        max_gain_unit  = spread_width - spread_debit      # max if spread → full width
        max_gain_total = max_gain_unit * lot_size * approved_lots

        # ── G7: Max possible gain must cover the session target ────────────
        # This replaces the old 1.5× R:R rule which was too restrictive.
        # A trade is viable as long as the spread *could* earn the target.
        if max_gain_total < target_rupees:
            last_fail_code = "TARGET_NOT_VIABLE"
            last_fail_text = (
                f"Max possible gain ₹{max_gain_total:.0f} < "
                f"session target ₹{target_rupees:.0f} for "
                f"{long_s}{opt_type}/{short_s}{opt_type}."
            )
            best_snapshot = {
                "bias": bias, "opt_type": opt_type,
                "candidate_rank": rank,
                "long_strike": long_s, "short_strike": short_s,
                "spread_width": spread_width,
                "long_price": round(long_p, 2), "short_price": round(short_p, 2),
                "spread_debit": round(spread_debit, 2),
                "approved_lots": approved_lots,
                "lot_size": lot_size,
                "max_loss_total": round(total_max_loss, 2),
                "max_gain_total": round(max_gain_total, 2),
                "target_rupees": round(target_rupees, 2),
                "risk_cap": round(risk_cap, 2),
                "failing_gate": "G7",
            }
            continue

        # ── All gates passed for this candidate → ENTER ───────────────────
        candidate = {
            "bias": bias,
            "opt_type": opt_type,
            "candidate_rank": rank,
            "long_strike": long_s,
            "short_strike": short_s,
            "spread_width": spread_width,
            "long_price": round(long_p, 2),
            "short_price": round(short_p, 2),
            "spread_debit": round(spread_debit, 2),
            "approved_lots": approved_lots,
            "lot_size": lot_size,
            "total_max_loss": round(total_max_loss, 2),
            "max_gain_total": round(max_gain_total, 2),
            "target_profit": round(target_rupees, 2),
            "expiry": str(expiry),
        }

        return GateResult(
            action="ENTER",
            reason_code="ENTER_TRADE",
            reason_text=(
                f"{bias} breakout confirmed at close {close:.2f}. "
                f"{long_s}{opt_type}@{long_p:.2f} / {short_s}{opt_type}@{short_p:.2f}. "
                f"Debit={spread_debit:.2f}, Lots={approved_lots}, "
                f"MaxLoss=₹{total_max_loss:.0f}, MaxGain=₹{max_gain_total:.0f}."
            ),
            candidate_structure=candidate,
            computed_max_loss=round(total_max_loss, 2),
            computed_target=round(target_rupees, 2),
            bias=bias,
            long_strike=long_s,
            short_strike=short_s,
            opt_type=opt_type,
            approved_lots=approved_lots,
            entry_debit=round(spread_debit, 2),
            lot_size=lot_size,
            expiry=expiry,
        )

    # No candidate passed G5–G7
    return GateResult(
        action="NO_TRADE",
        reason_code=last_fail_code,
        reason_text=last_fail_text,
        pre_entry_snapshot=best_snapshot,
    )
